feat: SQL review API for VCS workflow (#2966)
* chore: add sql review api to support vcs

* fix: lint

* fix: lint

* chore: add list pr file api

* chore: support sql advise

* chore: reset changes

* chore: check request token

* chore: update variable

* chore: update sql review

* chore: fix sql check

* chore: update comment

* chore: update github func

* chore: update test

* chore: resolve conflict

* chore: update test

* chore: add tests

* chore: fix test

* chore: update server/webhook.go

Co-authored-by: Joe Chen <jc@unknwon.io>

* chore: update vcs sql review api

* chore: update repo filter

* chore: update sql review ci

* chore: fix github vcs sql review

* chore: update sql reivew for gitlab

* fix: test

* fix: token comparison

* chore: address comment

* chore: revert changes for webhook

* Update plugin/vcs/github/github.go

* Update plugin/vcs/github/github.go

Co-authored-by: Joe Chen <jc@unknwon.io>
Co-authored-by: Danny Xu <98006139+d-bytebase@users.noreply.github.com>
Former-commit-id: 360aa687325fa799a406549e0fc2bd2a933c9f85

diff --git a/plugin/vcs/github/sql-review.yml b/plugin/vcs/github/sql-review.yml
--- a/plugin/vcs/github/sql-review.yml
+++ b/plugin/vcs/github/sql-review.yml
@@ -6,14 +6,34 @@ jobs:
     steps:
       - name: SQL advise
         run: |
-          pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
-          API="%s/pull/$pull_number"
+          API="%s"
+          TOKEN="${{ secrets.%s }}"
           echo "Start request $API"
 
-          response=$(curl -s --show-error -X GET "$API" -H "Content-type: application/json" -H "X-SQL-Review-Token: ${{ secrets.%s }}")
-          echo $response
-          status=$(echo $response | jq -r '.status')
-          content=$(echo $response | jq -r '.content')
+          pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
+          repository=`echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]'`
+          request_body=$(jq -n \
+            --arg repositoryId "$repository" \
+            --arg pullRequestId $pull_number \
+            --arg webURL "$GITHUB_SERVER_URL" \
+            '$ARGS.named')
+
+          response=$(curl -s -w "%%{http_code}" -X POST $API \
+            -H "X-SQL-Review-Token: $TOKEN" \
+            -H "Content-Type: application/json" \
+            -d "$request_body")
+          echo "::debug::response $response"
+
+          http_code=$(tail -n1 <<< "$response")
+          body=$(sed '$ d' <<< "$response")
+
+          if [ $http_code != 200 ]; then
+            echo ":error::Failed to check SQL with response code $http_code and body $body"
+            exit 1
+          fi
+
+          status=$(echo $body | jq -r '.status')
+          content=$(echo $body | jq -r '.content')
 
           while read message; do
             echo $message
